- name: Create VMware guest
  hosts: localhost
  connection: local
  gather_facts: False

  vars_prompt:
    - name: "vcenter"
      prompt: "vCenter hostname?"
      default: "10.78.60.63"
    - name: "user"
      prompt: "Enter username"
      default: "root"
      private: no
    - name: "pass"
      prompt: "Enter password"
      private: yes
    - name: "template"
      prompt: "Template?"
      default: "thomas_rhel_6.6-x86_64"
    - name: "cluster"
      prompt: "Cluster?"
      default: "cl03"
    - name: "resource_pool"
      prompt: "Resource pool?"
      default: "/"
    - name: "guest"
      prompt: "guest?"
      default: "thomas_ansible_template"

  tasks:
  - name: Make sure we have pip
    become: true
    apt: pkg=python-pip state=latest
  - name: Install Python modules
    become: true
    pip: name={{ item }} state=latest
    with_items:
      - pysphere
      - pyvmomi
  - name: Deploy guest from template
    vsphere_guest:
      vcenter_hostname: "{{ vcenter }}"
      username: "{{ user }}"
      password: "{{ pass }}"
      guest: "{{ guest }}"
      from_template: yes
      template_src: "{{ template }}"
      #cluster: "{{ cluster }}"
      resource_pool: "{{ resource_pool }}"
      validate_certs: no
